author: 若离QQ：2909998156
# 调试模式，用于寻找错误出现的坐标，默认为false
debug: false

host: 'smtp.qq.com'
email: ''
epassword: ''


#用户组配置
##################################################
# 温馨提示：请仔细注意每个模板是属于哪个任务类型的配置！##
##################################################
users:
  # 第一个用户配置
  # 以下配置为工作日志
  - user:
      # 任务类型（收集：0、签到：1、查寝：2、教师工作日志：3）
      type: 1
      #school 学校全称
      schoolName: 南京工程学院
      #username 学号或者工号
      username: ''
      #password 密码
      password: ''
      # 地址信息
      address: '江苏省南京市江宁区映霞路'
      #email 接受通知消息的邮箱
      email: ''
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 118.88729418288497
      #lat 纬度
      lat: 31.934772219705941
      abnormalReason: 在家
      checkTitle: 0
      # 表单信息
      forms:
        - form:
            title: 上午体温报告
            value: 36.0℃及以下
        - form:
            title: 下午体温报告
            value: 36.0℃及以下
#   # 第二个用户配置
#   # 以下配置为工作日志
#   - user:
#       # 任务类型（收集：0、签到：1、查寝：2、教师工作日志：3）
#       type: 1
#       #school 学校全称
#       schoolName: 南京工程学院
#       #username 学号或者工号
#       username: ''
#       #password 密码
#       password: ''
#       # 地址信息
#       address: '江苏省南京市江宁区映霞路'
#       #email 接受通知消息的邮箱
#       email: ''
#       # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
#       #lon 经度
#       lon: 118.88729418288497
#       #lat 纬度
#       lat: 31.934772219705941
#       abnormalReason: 在家
#       checkTitle: 0
#       # 表单信息
#       forms:
#         - form:
#             title: 上午体温报告
#             value: 36.0℃及以下
#         - form:
#             title: 下午体温报告
#             value: 36.0℃及以下
#    # 第三个用户配置
#   - user:
#       # 任务类型（收集：0、签到：1、查寝：2、教师工作日志：3）
#       type: 1
#       #school 学校全称
#       schoolName: 南京工程学院
#       #username 学号或者工号
#       username: ''
#       #password 密码
#       password: ''
#       # 地址信息
#       address: '江苏省南京市江宁区映霞路'
#       #email 接受通知消息的邮箱
#       email: ''
#       # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
#       #lon 经度
#       lon: 118.88729418288497
#       #lat 纬度
#       lat: 31.934772219705941
#       abnormalReason: 在家
#       checkTitle: 0
#       # 表单信息
#       forms:
#         - form:
#             title: 上午体温报告
#             value: 36.0℃及以下
#         - form:
#             title: 下午体温报告
#             value: 36.0℃及以下
#   # 第四个用户配置
#   # 以下配置为查寝
#   # 这里默认仅适配四川信息职业技术学院，其他学校自行修改
#   - user:
#       # 任务类型（收集：0、签到：1、查寝：2、教师工作日志：3）
#       type: 2
#       #school 学校全称
#       schoolName: 四川信息职业技术学院
#       #username 学号或者工号
#       username: ''
#       #password 密码
#       password: ''
#       # 地址信息
#       address: ''
#       #email 接受通知消息的邮箱
#       email: ''
#       # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
#       #lon 经度
#       lon: 105.895856
#       #lat 纬度
#       lat: 32.424037
#       #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
#       abnormalReason: ''
#       #photo 签到照片，不需要可不填，或者直接删除
#       photo: sign.jpg